fallback = ''

[matching]
'discord' = ''
'ArmCord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'Spotify' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'Thunar' = ''
'vivaldi-bin' = ''
'easyeffects' = '醙'
'EasyEffects' = '醙'
'youtube music' = ''
'youtube music' = ''
'vivaldi-stable' = ''
'electron' = ''
'0x2C00003' = ''
' = ''
'0x2C00003' =
'260082' = ''
'260082' = ''
